// Create Todo type
export const TODO_FAILED = "TODO_FAILED";

export const TODO_GET_REQ = "TODO_GET_REQ";
export const TODO_GET_SUCCESS = "TODO_GET_SUCCESS";
export const TODO_GET_ERROR = "TODO_GET_ERROR";

export const TODO_ADD_REQ = "TODO_ADD_REQ";
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS";
export const TODO_ADD_ERROR = "TODO_ADD_ERROR";

export const TODO_CANCEL_PENDING_SUCCESS = "TODO_CANCEL_PENDING_SUCCESS";
export const TODO_COMPLETE_PENDING_SUCCESS = "TODO_COMPLETE_PENDING_SUCCESS";
export const TODO_PENDING_FAILED = "TODO_PENDING_FAILED";

export const TODO_CANCEL_COMPLETE_SUCCESS = "TODO_CANCEL_COMPLETE_SUCCESS";
export const TODO_PENDING_COMPLETE_SUCCESS = "TODO_PENDING_COMPLETE_SUCCESS";
export const TODO_COMPLETE_FAILED = "TODO_COMPLETE_FAILED";

export const TODO_PENDING_CANCEL_SUCCESS = "TODO_PENDING_CANCEL_SUCCESS";
export const TODO_COMPLETE_CANCEL_SUCCESS = "TODO_COMPLETE_CANCEL_SUCCESS";
export const TODO_CANCEL_FAILED = "TODO_CANCEL_FAILED";

export const TODO_DELETE_SUCCESS_CANCEL = "TODO_DELETE_SUCCESS_CANCEL";
export const TODO_DELETE_SUCCESS_PENDING = "TODO_DELETE_SUCCESS_PENDING";
export const TODO_DELETE_SUCCESS_COMPLETE = "TODO_DELETE_SUCCESS_COMPLETE";
export const TODO_DELETE_FAILED = "TODO_DELETE_FAILED";
